### ISSUE TITLE
数据归档.ipynb 和 数据可视化.ipynb 说明不全

### ISSUE THREAD

**Issue by pjrobertson** [HeQinWill/CNEMC#1]
两个jupyter notebook 都有提到cnemc.h5，但没有说明如何制造cnemc.h5 文件。

希望可以在readme加一句话

谢谢！

**Comment by HeQinWill** [comment]
cnemc.h5 为归档文件  
数据归档.ipynb 中会先判断它是否存在 `Path('cnemc.h5').exists() `  
如果该文件（一般自己指定的本地路径）存在则会继续追加文件   
如果不存在则直接会创建该文件
